### ISSUE TITLE
Orientierungslinie 

### ISSUE THREAD

**Issue by 0scarZulu** [jason0611/FS22_HeadlandManagement#107]
Aloha :) 
 vorweg danke für deine Ergänzungen mit der Wahl der O-Linie und das man den Frontsensor deaktivieren kann :) 

Ich habe jetzt mal die O-Linie auf den "Bearbeiteten Bereich" gesetzt aber irgendwie nimmt er dennoch den Feldrand und lenkt komplett nach rechts ein. Hab ich da einen Fehler im Denken? 

![image](https://user-images.githubusercontent.com/78980660/225453631-de4ea066-29ba-44e0-b74f-e3dfcddb96df.png)

![image](https://user-images.githubusercontent.com/78980660/225453759-99d90bf1-d8f6-487e-8606-6dcd945fcf7e.png)

Er nimmt dann irgendwie als Abstand eine komplette Arbeitsbreite.. Das finde ich komisch. 

![image](https://user-images.githubusercontent.com/78980660/225454016-c6dbacad-6a9e-4b20-bb0f-db8f783e8e4b.png)

Cheers 
Oz

**Comment by jason0611** [comment]
Mit welcher Version hast Du es denn probiert? Da waren noch ein paar Fehler, die ich heute im Laufe des Tages behoben habe. Die jetzt aktuelle Version hier sollte da schon besser funktionieren.

**Comment by 0scarZulu** [comment]
Hm naja irgendwie nicht. Hab mir gerde ebend nochmal alles runtergeladen aber irgendwie will er bei der Auswahl "Bearbeiteter Bereich" nicht so ganz ordentlich fahren :D 
![image](https://user-images.githubusercontent.com/78980660/226914812-f656f2ef-de38-4d35-82dd-3555f25e9a6c.png)

**Comment by jason0611** [comment]
Die Wegeführung entlang der Bearbeitungslinie muss ich nochmal überarbeiten. Derzeit vergleiche ich den Untergrund des Fahrzeugs mit dem Untergrund des Messpunkts. Leider ändert sich die Kennzeichnung des Untergrunds bereits dann, wenn sich die Arbeitsrichtung ändert, weshalb dieser Ansatz nicht funktioniert. Bis zur fertigen Überarbeitung benötigt es aber noch etwas Zeit, derzeit versuche ich erst einmal das Prinzip zu verstehen, nachdem die Bodentypen vergeben werden.

**Comment by 0scarZulu** [comment]
Ah ok.. Na gut dann nutze ich den klassischen Weg weiter :) Aber cool das du dran bleibst ...

**Comment by jason0611** [comment]
Bitte gerne nochmal mit der aktuellsten Version ausprobieren. Es scheint jetzt ganz gut zu funktionieren. :-)

**Comment by 0scarZulu** [comment]
Okay cool .. Hatte schon bevor du geschrieben hattest gesehen das es was neues gibt :) Was genau hast du jetzt angepasst? 
Cheers

**Comment by jason0611** [comment]
Hi,
ich habe die Funktion, mit der ich den Bodenstatus ermittle, geändert. Die zuvor genutzte Funktion kannte für jede kleinste Änderung des Bodens verschiedene Werte, dazu zählte dann schon, mit welchem Bodenwinkel eine Bearbeitung durchgeführt wurde. Die jetzt verwendete Funktion unterscheidet nur zwischen den Bearbeitungsstatus, die man auch von der Karte im Spiel kennt und ist somit wesentlich besser für die Konturführung geeignet.
Da die genutzte Funktion nicht in der LUA-Dokumentation des Spiels enthalten ist, musste ich sie a) zunächst finden und dann b) herausfinden, wie sie genau arbeitet. :-)

**Comment by SAM24986** [comment]
Hey Martin,
Ich hab mir mal wieder die Master-Version geladen, das Entwickler Debug ist immer eingeschaltet? Kann man das abstellen, es füllt die Log doch ordentlich. Ansonsten wie vorher auch schon... mega Arbeit
Gruß
Sönke

**Comment by jason0611** [comment]
Hallo Sönke,
Danke für das Feedback. 
In der Entwicklerversion ist das Debugging immer aktiv. Du kannst in der headlandManagement.lua den Debuglevel z.B. auf 1 stellen, dann reduzierst Du die Logeinträge schon deutlich.
Viele Grüße,
Martin

**Comment by SAM24986** [comment]
Ich muss blind sein, aber in der Management.lua finde ich keinen DebugLevel.

**Comment by jason0611** [comment]
Schau mal in Zeile 21. 🙂

**Comment by SAM24986** [comment]
Danke, hätte ich jetzt nicht so gefunden. Was passiert wenn man den Wert auf 0 setzt?

**Comment by jason0611** [comment]
Wenn Du den Wert davor auf `false` setzt, wird das Debugging ganz abgeschaltet. Dann kann der Wert dahinter ganz entfallen.
