### ISSUE TITLE
Head Track System Track IR5 disabled when HLM active / Head Track-System Track IR5 deaktiviert, wenn HLM aktiv ist

### ISSUE THREAD

**Issue by Salihoi1** [jason0611/FS22_HeadlandManagement#109]
Hello
I have the problem that my head track system (Track IR5) switches off as soon as I activate HLM in the vehicle. I have already checked whether it is perhaps due to a double assignment of the keys. But it is not. The software of the head track system still reacts, but in the game the cockpit view is frozen and I can only look around with mouse/coolihat.

Does anyone know what it could be?

Kind regards
Marcel

---DEUTSCH---
Hallo 
Ich habe das Problem, dass sich mein Head Track System (Track IR5) ausschaltet, sobald ich HLM im Fahrzeug aktiviere. Ich habe schon geprüft, ob es vielleicht an einer Doppelbelegung der Tasten liegt. Ist es aber nicht. Die Software des Head-Track-System reagiert weiterhin, aber im Spiel wird die Cockpitansicht eingefrohren und ich kann mich nur noch mit Maus/Coolihat umsehen.

Weiss jemand woran es liegen könnte?

Grüsse
Marcel

**Comment by jason0611** [comment]
Hello,

thank you for your report.
Please provide a logfile of your game while the problem occurs. Have you tested it without any mods but HeadlandManagement? Because I know that it works fine for many players with Track IR5.

Kind regards, 
Martin

PS: You can write in english or german as you like, I'm a native german speaker. :-)

**Comment by Salihoi1** [comment]
Hallo
Ich habe festgestellt, dass beim aktivieren des HLM im Traktor, die 3rd Personkamera an Ort stehen bleibt und das Fahrzeug fàhrt aus dem Bild. Es ist nicht steuerbar, solange dass HLM aktiviert ist.
Log hat nur folgende Zeilen:
2023-05-06 16:25 Error: Running LUA method 'update'.
C:/Users/USERNAME/FOLDER/FOLDER/My Games/FarmingSimulator2022/mods/FS22_HeadlandManagement/headlandManagement.lua:1181: attempt to compare number with nil

**Comment by Salihoi1** [comment]
Der Fehler kommt also nicht nur, wenn ich das Headtrack-System nutze. Muss an etwas anderem liegen.

**Comment by jason0611** [comment]
Um den Fehler eingrenzen oder sogar nachstellen zu können, benötige ich bitte das Logfile des Spiels, nachdem der Fehler aufgetreten ist.

**Comment by Salihoi1** [comment]
[log.txt](https://github.com/jason0611/FS22_HeadlandManagement/files/11415004/log.txt)

**Comment by Salihoi1** [comment]
Hier das Log-File.
[log.txt](https://github.com/jason0611/FS22_HeadlandManagement/files/11415021/log.txt)
Das Hauptproblem ist die stehenbleibende Kamera.

**Comment by jason0611** [comment]
Die stehenbleibende Kamera ist nur das Symptom, verursacht wird das dadurch, dass Werte von EnhancedVehicle leer sind, die nicht leer sein sollten.
Kannst Du das bitte einmal nur mit HeadlandManagement, EnhancedVehicle und HeadTracking versuchen und dazu das Log hier einstellen? Ich habe leider kein HeadTracking-System, daher fällt das direkte Reproduzieren schwer. Mir ist wichtig, ob der Wert in EnhancedVehicle auch ohne andere Mods leer sein kann.

**Comment by Salihoi1** [comment]
Aktive Mods waren nur  HeadlandManagement und EnhancedVehicle
Kamera Innenansicht reagiert nicht auf das Headtrack-System, sobald HLM eingeschaltet wird.
Hier das Log-file.
[log.txt](https://github.com/jason0611/FS22_HeadlandManagement/files/11415257/log.txt)

Wenn HLM als einzige Mod aktiv ist. funktioniert alles bestens. Muss wohl am EV liegen.
Hier die Log
[log.txt](https://github.com/jason0611/FS22_HeadlandManagement/files/11415264/log.txt)

**Comment by jason0611** [comment]
Verhält es sich mit dieser Version besser?
[FS22_HeadlandManagement.zip](https://github.com/jason0611/FS22_HeadlandManagement/files/11415802/FS22_HeadlandManagement.zip)

**Comment by Salihoi1** [comment]
Ich sehe das Problem als behoben. Herzlichen Dank für die schnelle und kompetente Hilfe.

Diese Version funktioniert mit EnhancedVehicle wie auch mit VCA (Einzeln getestet) sowie allen Mods aktiv.
Log hier
[log.txt](https://github.com/jason0611/FS22_HeadlandManagement/files/11425349/log.txt)


Im Spiel hatte ich eine Anomalie mit dem Pflug-Mod Rabe Albatros. Der Traktor viel ins Bodenlose gleich beim ersten Spur mit dem Pflug. Der Traktor  viel ca 12000km/h schnell und rotierte.
Dieser Fehler konnte ich mit den andern Pflügen nicht reproduzieren. Deshalb gehe ich davon aus, dass es nicht mit HLM zu tun hat.  Dabei konnte ich die Geräte nur über das Shop Menu verkaufen und musste sie neu kaufen. 
Zeitabschnitt im Log zwischen 22:50Uhr - 22:55Uhr

**Comment by jason0611** [comment]
Danke für die Rückmeldung. Dann sehe ich den Fehler ebenfalls als behoben an.
Die Anomalie mit dem Pflug sehe ebenfalls in keinem Zusammenhang mit HLM. HLM greift zu keinem Zeitpunkt in die Fahrzeug-Physik ein und es sind keine entsprechenden Fehler im Log enthalten.
