### ISSUE TITLE
Autoturn

### ISSUE THREAD

**Issue by 0scarZulu** [jason0611/FS22_HeadlandManagement#110]
Aloha, 

ich nutze rege und mit voller Begeisterung dein HM. Jetzt stellt sich mir die Frage, ob zusätlich zu dem automatisch ausheben beim erreichen des Vorgewendes noch die Möglichkeit Einzug halten wird des Autoturns. Also quasi dem automatisch lenken in die nächste Spur (x+0 oder x+1). In der Theorie ist ja mit der Möglichkeit das HM das GPS wieder reaktivieren kann  ein wichtiger Part gegeben für den Autoturn :) Ja ich weiß auch das EV das wohl kann aber ich persönlich finde das einstellen des GPS bzw. der Spurführung durch umständlich. :D 

Cheers
Oz

**Comment by jason0611** [comment]
Hallo,
Autoturn ist schon seit geraumer Zeit ins Headland Management integriert, wenn die GPS-Funktion von VCA oder EV genutzt wird:
 
![fsScreen_2023_04_05_23_18_33](https://user-images.githubusercontent.com/12356451/230214005-94c25ae3-7520-4e64-bcc9-0686d88d1b00.png)

![fsScreen_2023_04_05_23_16_58](https://user-images.githubusercontent.com/12356451/230213992-b3063fb2-0d74-4279-a265-0fca65875a0c.png)

In beiden Fällen wird entweder die jeweilige Autoturn-Funktion von VCA oder von EV genutzt, aber durch das Headland Management ausgelöst.

Viele Grüße,
Martin

**Comment by 0scarZulu** [comment]
Hm ok. Also muss ich zwingend, um diese Funktion zu haben im HM einen der beiden Mods zusätzlich nutzen. Schade aber ok dann ist dem so. Dann muss ich wohl weiter von allein wenden 😂 Danke für deine Antwort.

Cheers 🥃 
Oz
