### ISSUE TITLE
Mögliche Erweiterung

### ISSUE THREAD

**Issue by Slive1993** [jason0611/FS22_HeadlandManagement#113]
Guten Tag,

Zuerst einmal herzlichen Dank für diesen super Mod.
Ich hoffe ich bin hier am richtigen Ort.
Ich wollte fragen, ob es möglich wäre, dass bei einem Drescher im Vorgewende Modus die Strohablage Deaktiviert wird?

Beste Grüsse

**Comment by jason0611** [comment]
Hi, 

Danke für das Feedback.

Möglich wäre das, ich bin mir aber nicht sicher, ob das sinnvoll ist: Das Umschalten von Schwadablage auf Strohhäcksler dauert im Spiel meist eine Weile und bis das abgeschlossen ist, dürfte in vielen Fällen der Wendevorgang bereits abgeschlossen sein. Mit dem Ausheben des Schneidwerks stockt ja ohnehin die Zufuhr und die Ablage wird nur noch entleert. Auch das dauert seine Zeit. Ein schlichtes "an/aus" der Strohablage lässt sich leider nicht umsetzen, dazu fehlt im Spiel die Funktion.

Viele Grüße,
Martin

**Comment by jason0611** [comment]
Ich habe das nochmal näher angesehen: Das abrupte Abschalten der Schwadablage ist nicht möglich, nach Ausheben des Schneidwerks läuft die interne Verarbeitung noch leer und erzeugt entsprechend auch Stroh. Da im Vorgewende einzugreifen, ist nicht ohne weiteres machbar.

**Comment by Slive1993** [comment]
Hallo Martin,
Besten Dank für deine Rückmeldung. Ich war der Meinung, dass so bald von Schwadablage auch Stohverteilung umgeschalten wird, die Strohberteilung beginnt. Ich kann mich aber auch irren. Momentan habe ich kein Rechner zur Verfügung um es zu Testen. Aber wenn du es dir angeschaut hast, wird es so stimmen.

Freundliche Grüsse

Simon Limacher
________________________________
Von: Glowins Modschmiede ***@***.***>
Gesendet: Thursday, June 15, 2023 2:13:35 PM
An: jason0611/FS22_HeadlandManagement ***@***.***>
Cc: Slive1993 ***@***.***>; Author ***@***.***>
Betreff: Re: [jason0611/FS22_HeadlandManagement] Mögliche Erweiterung (Issue #113)


Ich habe das nochmal näher angesehen: Das abrupte Abschalten der Schwadablage ist nicht möglich, nach Ausheben des Schneidwerks läuft die interne Verarbeitung noch leer und erzeugt entsprechend auch Stroh. Da im Vorgewende einzugreifen, ist nicht ohne weiteres machbar.
