### ISSUE TITLE
nachträgliches einstellen des Abstandes

### ISSUE THREAD

**Issue by foreverls19** [jason0611/FS22_HeadlandManagement#117]
Hallo,
wäre es möglich eine nachträgliche manuelle Justierung des Abstandes einzubauen,
das Problem wo ich immer habe ist wenn der Abstand zum bearbeitetem Grund nicht ganz passt.
Oder mache ich da vielleicht auch was falsch.
![fsScreen_2023_08_15_21_29_16](https://github.com/jason0611/FS22_HeadlandManagement/assets/42800237/ab9e5490-e66d-45c2-906a-0ee0df678505)

**Comment by jason0611** [comment]
In der Einstellung "Aktuellen Abstand beibehalten" wird der Abstand zum bearbeiteten Bereich einmal bei Aktivierung des Feldmodus gemessen und dann beibehalten. Das sollte sehr exakt funktionieren, solange das System den bearbeiteten Bereich auch erkennen kann. Ich plane aber, zukünftig auch noch die manuelle Eingabe zu ermöglichen, dann wäre der Abstand optional frei einstellbar.
