### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by Haegglun** [jason0611/FS22_HeadlandManagement#12]
Guten Tag,
Wie läuft die Einstellung genau ab, fährt man erst das Vorgewende während der Mod aktiviert ist und dann schaltet man es aus, und derSchlepper erkennt dann das Vorgewende und hebt dann automatisch aus oder wie funkioniert das?

**Comment by Gariot** [comment]
Ich kann jetzt nur mutmaßen, darum meine Aussage bitte mit vorsicht geniessen.

So wie ich es verstanden habe hilft dir die mod einfach nur mehrere arbeitsschritte auf einen Knopfdruck zu erledigen. Erreichst du dein gewuenschtes vorgewende aktivierst du mit shift-x die mod. Die mod deaktiviert z.b. dann dein GPS, rotiert dir den pflug oder schaltet die saehmaschine aus und faehrt die hydraulik hoch. Ausserdem senkt sie deine geschwindigkeit auf 5 km/h (default. Kannst du aber einstellen). Dann kannst du gemuetlich in die naechste bahn wenden und deaktivierst die mod wieder. Die senkt den pflug dann oder schaltet die saehmaschine wieder an und senkt sie. Ausserdem aktiviert sie auch GPS wieder und laesst dich wieder schneller fahren.

Ist jedenfalls ganz nett :)


Ich dachte zuerst das die Mod das Feld erkennt und mich dann automatisch in die naechste bahn lenkt und selbststaendig dann ein vorgewende erzeugt. Aber hey, was solls :D

**Comment by jason0611** [comment]
Ein Vorgewendemanagement dient in erster Linie der Bedienung der Arbeitsgeräte im Wendevorgang, also bei Erreichen des Vorgewendes. Moderne GPS-Systeme lassen sich damit koppeln, so dass dann bei Erreichen des Vorgewendet automatisch die zugehörigen Arbeitsschritte gestartet werden. Leider gibt es im LS19 keinen GPS-Mod, der das vermag.
Manchmal ist auch der Wendevorgang selbst Bestandteil des Managements, dies habe ich noch auf der Toto-Liste, ohne zu wissen, ob das wirklich im LS realisierbar ist. 
Was ich aber als Idee mal mitnehme ist, das ich prüfe, ob ich den Vorgewendetrigger von GuidanceSteering als möglichen Auslöser nutzen kann. Das wäre dann was für eine Folgeversion. :-)

**Comment by jason0611** [comment]
Danke. Wenn technisch machbar, werde ich die Mod auch in den 22er bringen. :-)

**Comment by Haegglun** [comment]
Ist es auch möglich, das der mod die lenkungsarten ändert z. B. Hundegang von rechts nach links,? Wäre gerade beim rüben roden nice

**Comment by jason0611** [comment]
> Ist es auch möglich, das der mod die lenkungsarten ändert z. B. Hundegang von rechts nach links,? Wäre gerade beim rüben roden nice

Coole Idee. Das sollte realisierbar sein, ich nehme es mit auf die Liste. :-)

**Comment by jason0611** [comment]
> > ob das wirklich im LS realisierbar ist. Was ich aber als Idee mal mitnehme ist, das ich prüfe, ob ich den Vorgewendetrigger von GuidanceSteering als möglichen Auslöser nutzen kann. Das wäre dann was für eine Folgeversion. :-)
> 
> Ohne, dass ich eine Ahnung vom Modden hab (vom programmieren generell schon), müsste sich mit dem GPS ein Autoturn realisieren lassen. Man müsste halt "nur" berechnen wie weit die Maschine ins Vorgewende fahren muss um den Turn in die nächste (vlt auch irwann mal jede x.) Spur zu schaffen...

Das ist leider nicht ganz so trivial: In Abhängigkeit von Wendekreis und Arbeitsbreite gibt es mehrere Strategien, eine Wende anzufahren. Hier müsste jeweils die richtige Logik implementiert werden. CoursePlay zeigt eindrucksvoll, wie herausfordernd das ist. Ich habe es mit auf die ToDo-Liste gesetzt, aber ob es neben Beruf und Familie realisierbar ist, vermag ich gerade nicht zu sagen.
