### ISSUE TITLE
Manuelle Vorgewendebreite / Konturführung 

### ISSUE THREAD

**Issue by MRNOBODY515** [jason0611/FS22_HeadlandManagement#121]
Servus! Eine Bitte hätte ich. Wäre es möglich beim Abstand zum Feldrand eine freie Wahl einzugeben? Die festen Werte sind schon sehr hilfreich!  Beispiel: ich hab 12 Meter Breite also setzte ich die erste Bahn auf 6 Meter. Danach brauche ich die Bahn auf 18 Meter. Bekomme aber nur 9/15/21 zur Auswahl. Also muss ich zwangsläufig mit aktuellem Abstand zum Feldrand fahren was je nachdem wie man gerade steht nicht immer auf Anhieb so ganz passt.
Und eine Frage. Was ändert sich eigentlich wenn der Frontsensor aktiv ist?

Grüße und Dank!

**Comment by jason0611** [comment]
Hallo, die manuelle Eingabe des Abstands werde ich mit implementieren. 
Eigentlich sollten zwar die errechneten Abstände (halbe Breite, ganze Breite für ProSeed, und dann jeweils 1.5, 2.5, 3.5 usw.) ausreichen, aber irgendwie funktioniert die Ermittlung der Arbeitsbreite nicht zuverlässig.

**Comment by MRNOBODY515** [comment]
Super! Vielen Dank! Und weiter so. Wirklich ein genialer Mod!
