### ISSUE TITLE
Frontgewichte werden als Gerät behandelt

### ISSUE THREAD

**Issue by worker2419** [jason0611/FS22_HeadlandManagement#15]
Version 1.0.1.0. 
Ein an den Trecker angebautes Gewicht wird als Gerät behandelt. Im Verlauf wird die Geschwindigkeit verringert, VCA Führung abgeschaltet und die angehängte Sämaschine ausgehoben. Nach den Manöver geht die Geschwindigkeit wieder hoch, Spurführung wird aktiviert, Sämaschine UND Gewicht abgesenkt.
Claas und Gewicht aus dem DLC, Sämaschine Mod

**Comment by jason0611** [comment]
Danke für den Hinweis. Der Fehler ist mir auch aufgefallen, eine Lösung ist in Arbeit. :-)

**Comment by jason0611** [comment]
Bitte prüfe mal, ob der Fehler mit der beigefügten Version behoben ist. Bei mir tritt er damit nicht mehr auf.
[FS19_HeadlandManagement.zip](https://github.com/jason0611/FS19_HeadlandManagement/files/7360946/FS19_HeadlandManagement.zip)

**Comment by cwhandersen** [comment]
What map is that?

**Comment by cwhandersen** [comment]
Thank you.

**Comment by worker2419** [comment]
Ja, das ist so richtig beschrieben.

**Comment by jason0611** [comment]
Noch ein Tipp: In der ModHub-Version hilft es eventuell, das Gewicht kurz abzukoppeln und danach wieder anzukoppeln, damit es sich wie erwartet verhält.
