### ISSUE TITLE
Control UI broked on Ultrawide

### ISSUE THREAD

**Issue by BarryCarlyon** [jason0611/FS22_HeadlandManagement#22]
As attached. The `Ctrl+shift+x` menu doesn't "fit" on a ultrawide resolution.

![20211026012257_1](https://user-images.githubusercontent.com/20999/138788291-b06eb9b5-1109-44ab-9e90-92a7ca0aac4d.jpg)

**Comment by jason0611** [comment]
Did you find out something new on this issue? My son's PC doesn't allow more than 1920x1080, so I couldn't investigate further. Are you using other mods with a GUI that fits right? If so, I could look into them to adapt my GUI settings if possible.

**Comment by jason0611** [comment]
I've made some gui optimizations. Would you please give it a try? I would appreciate this. :-)
[FS19_HeadlandManagement.zip](https://github.com/jason0611/FS19_HeadlandManagement/files/7558639/FS19_HeadlandManagement.zip)

**Comment by jason0611** [comment]
Please try out the today coming version from ModHub. I've rearranged the gui items, so that all items should align to the center, even on your super-sized resolution. If it's not fixed, feel free to re-open this issue.
