### ISSUE TITLE
Unable to open gui 

### ISSUE THREAD

**Issue by Cris5791** [jason0611/FS22_HeadlandManagement#38]
Hi, I have a problem. I am currently testing version 1.9.1.8, but even using previous versions I can no longer open the graphical interface and the key combination assigned which is the default one does not appear in the F1 menu. I tried a new save game with only this mod installed but nothing, reset the assigned keys, nothing. The loading of the mod seems to be correct, the only errors are these.

Error: Can't load resource 'F: / FS22 mod / FS22_HeadlandManagement / gui / hlm_gui.dds'.
Error: Can't load resource 'F: / FS22 mod / FS22_HeadlandManagement / gui / hlm_auto.dds'.

Can you help me? This is probably one of the coolest mods I've used so far.
Thanks.

**Comment by jason0611** [comment]
Have you configured Headland Management into your vehicle, either in the shop or in the workshop?

**Comment by jason0611** [comment]
In some previous versions there was a bug with the configurations. Please try the most actual version: 
[FS22_HeadlandManagement.zip](https://github.com/jason0611/FS22_HeadlandManagement/files/7688231/FS22_HeadlandManagement.zip)

**Comment by Cris5791** [comment]
Forgive me, as early revisions were available without purchase / configuration I didn't realize it was introduced. It works properly.
Thank you very much and I hope you continue to develop.
