### ISSUE TITLE
Debug menu active over hud when GS mod active

### ISSUE THREAD

**Issue by Hammy-Potter** [jason0611/FS22_HeadlandManagement#44]
![Inked1248130_20211212210809_1_LI](https://user-images.githubusercontent.com/96027320/145732491-5a17e4a8-15e5-458e-b3d4-8397f0efdab3.jpg)
 This debug info is always active if guidance steering mod is active. If the GS mod is inactive, or VCA mod active, this disappears, also headlands management is not available to buy in the workshop.

**Comment by jason0611** [comment]
Hello Hammy-Potter,
you are using a development version, so active debug informations are no issue. ;-)
Please use the most actual version which also is waiting for ModHub-Release: 
[FS22_HeadlandManagement.zip](https://github.com/jason0611/FS22_HeadlandManagement/files/7702116/FS22_HeadlandManagement.zip)
