### ISSUE TITLE
Spurführung/Wenden-Verbsserung

### ISSUE THREAD

**Issue by Larsinator78** [jason0611/FS22_HeadlandManagement#52]
Mahlzeit zusammen,
erstmal geiler Mod ist einfach wie bei in meinem Fendt. Wo ich nur noch die Tasten "Stop" and "Go" drücken muss, um das Gerät abzusenken und GPS zu aktivieren. Es erleichtert das Leben ungemein.
Jedoch würde mich für einen Punkt/Funktion eine Veränderung, Verbesserung oder zusätzliche Option wünschen.
Wenn ich ein Feld bearbeite, bevorzuge ich es selbst zu wenden und beende die GPS oder VCA Spürführung immer über ein Einlenken. Jedoch wenn ich in die neue Bahn einfahre und über das Headland Mangement wieder die Spurführungen aktivieren geht dies nicht sondern ich muss die Spurführungen wieder manuell aktivieren.
Vielleicht ist es möglich eine Option zu erstellen, in dieser würde der Vorgewende-Modus durch eine Lenkbewegung aktiviert oder vielleicht gibt es auch eine andere Möglichkeit.

Mit freundlichen Grüßen

**Comment by jason0611** [comment]
Hallo,
Danke für das Feedback. :-) In der Tat habe ich mich bei der Idee von Fendt inspirieren lassen, wenn ich auch selbst nicht in der Landwirtschaft tätig bin.
Hast Du mal versucht, das Vorgewende Management in den Vorgewendemodus zu schalten (also es zu aktivieren) bevor Du den Lenkeinschlag machst? In diesem Fall wird die Spurführung nämlich durch das Vorgewende Management beendet und dann auch bei Rückkehr in den Feldmodus (also beim deaktivieren) wieder aktiviert. 
Du kannst Dir Vorgewendemodus und Feldmodus auch auf zwei getrennte Tasten legen, dadurch würde es dem "Go/Stop" am Fendt nochmal etwas ähnlicher.
Viele Grüße,
Martin

**Comment by jason0611** [comment]
Noch eine kleine Ergänzung: Das Vorgewende Management über den Lenkeinschlag zu aktivieren, wäre grundsätzlich machbar. Dennoch deaktiviert der Lenkeinschlag zusätzlich die Spurführung, daher wäre nichts gewonnen.
Um das zu verhindern ist eine Anpassung von "Guidance Steering" notwendig.
