### ISSUE TITLE
Automatische Installation vom Headland Management in Missions Fahrzeuge

### ISSUE THREAD

**Issue by PapaTim68** [jason0611/FS22_HeadlandManagement#55]
Moin,
mir ist eine Idee bzw. ein Verbesserungsvorschlag gekommen. Soweit ich weiß, hat Guidance Steering implementiert das GPS in allen Fahrzeugen, welche für Feld Aufträge ausgeliehen werden, wo möglich das GPS Modul aktiviert ist. Es wäre ja schön, wenn dies fürs Vorgewende Management ebenfalls gelten würde.

Grüße,
Tim

**Comment by jason0611** [comment]
Das muss ich mir mal näher anschauen. Bei Guidance Steering war das zuletzt noch recht fehlerträchtig, ich weiss nicht, ob Wopster das schon komplett im Griff hat. Kommt aber definitiv auch auf die Liste. :-)

**Comment by jason0611** [comment]
In der aktuellen Dev-Version ist das Vorgewende Management nun in Missionsfahrzeugen vorhanden. Die Bereitstellung auch im ModHub erfolgt demnächst ebenfalls.
