### ISSUE TITLE
Einstellungen lassen sich nicht öffnen

### ISSUE THREAD

**Issue by luxstef** [jason0611/FS22_HeadlandManagement#60]
Ich habe VCA, GPS und Headland Management aktiviert und komme nicht in die Einstellungen des Headland management. Auch die Änderung der Tastenkombination für die Einstellungen führte leider nicht zum Erfolg. Ist es möglich, dass sich die 3 mods hier gegenseitig stören? Die log war/ist fehlerfrei...

Fehler gefunden.... wer lesen kann ist klar im Vorteil ;-) Ohne Kauf der Option kann man natürlich auch nichts einstellen - Sorry!!

**Comment by jason0611** [comment]
Kann passieren. ;-)
