### ISSUE TITLE
Option not showing on custom tractors

### ISSUE THREAD

**Issue by themob05** [jason0611/FS22_HeadlandManagement#61]
Im noticing that on the tractors I've modified the xml for paint and HP gain that the Headland management option does not appear in the store. Upon loading the game the log shows it being added as a config option as well as when in the store it is also showing as if it should be there in the log, however, the option isn't present. I am able to go in and edit the vehicle xml to enable it and it indeed then does work.

**Comment by jason0611** [comment]
Hello,
please add your complete log file, so that I can try to identify the root cause.

**Comment by jason0611** [comment]
As example, please add one modified vehicle's xml-file, too.

**Comment by themob05** [comment]
I will provide a log when I get internet back. I have however concluded that it has to do with the mods being in a custom category.

**Comment by jason0611** [comment]
If you have changed the vehicle's category to a custom one, then your log is no longer needed:
Headland Management is fixed to the standard categories of vehicles, which usually will provide such a function.
To use Headland Management in your modded vehicles, just use one of the standard categories, or add your category manually to the HeadlandManagement.lua. This should be very easy, you will find it starting in line 60.
Best example will be the JOHNDEEREPACK entry.
