### ISSUE TITLE
Trigger Anzeige nach Update auf aktuellste Version

### ISSUE THREAD

**Issue by 0scarZulu** [jason0611/FS22_HeadlandManagement#65]
Moin :) 

nachdem ich die aktuellste Version gezogen habe gestern Abend erscheinen bei mir an dem Attachern sowie bei den Geräten am Ende der Workarea  diese weißen Quader.  Wie bekomme ich die weg? :D 

![image](https://user-images.githubusercontent.com/78980660/150113561-673af93e-c6fc-4bbe-ae34-97d15f19ee6d.png)

**Comment by Kynuska** [comment]
Hallo.
Bei mir das gleiche Problem.
Kynuska

**Comment by jason0611** [comment]
Hallo zusammen,
bitte nochmal die neueste Version laden. Ich hatte vergessen, den "Forschungsteil" auszukommentieren.
