### ISSUE TITLE
keine HLM in Modschleppern mit geänderter VehiceType

### ISSUE THREAD

**Issue by 0scarZulu** [jason0611/FS22_HeadlandManagement#68]
Moin, HLM ist im Shop nicht wählbar wenn in der Moddesc ein VehicleTyp angepasst wird. Auch wenn als parent tractor gewählt wird erscheint HLM nicht im Shop zu Auswahl.

**Comment by 0scarZulu** [comment]
okay dann wird es daran liegen das diese eigenen Kategorien haben. Kann man das schnell beheben?

**Comment by jason0611** [comment]
Am besten einfach ins Skript einfügen. Die Kategorien stehen in der HeadlandManagement.lua in den Zeilen 75-88 (Dev-Version). Der Eintrag sollte selbsterklärend sein, einfach an den anderes Einträgen dort orientieren. :-)

**Comment by jason0611** [comment]
Einfach mal ausprobieren. Der vorhandene Eintrag ist noch aus dem 19er und funktionierte dort tadellos. Im 22er habe ich Ifkos JohnDeerePack noch nicht testen können.
