### ISSUE TITLE
AutoTurn bei Guidance Steering geplant? 

### ISSUE THREAD

**Issue by 0scarZulu** [jason0611/FS22_HeadlandManagement#69]
Moin :) Ich bin immer noch am rumtesten und werkeln welche SPurführung denn nun für mich am besten ist und hänge derzeit, weil ja auch gestern eine neue Version kam, bei Guidance Steering. 

Nun ist meine Frage, ob denn geplant ist auch ein Autoturn Aus meiner Sicht würde es den Begriff Vorgewende Management vollumfänglich erweitern.

**Comment by jason0611** [comment]
Wenn GS das als Funktion anbietet, werde ich es sofort unterstützen, falls möglich. Offenbar war diese Funktion ursprünglich mal geplant, wurde aber bisher noch nicht realisiert.
Ich werde im Vorgewende Management keine eigene Auto-Turn-Funktion realisieren, dafür müsste ich nämlich auch eine eigene GPS-Funktion bauen.
