### ISSUE TITLE
Two point turn not functioning properly with VCA

### ISSUE THREAD

**Issue by xVirusXx** [jason0611/FS22_HeadlandManagement#78]
I cannot get two point turning to work. It still executes a full turn.

**Comment by jason0611** [comment]
Which version (ModHub or GitHub) are you using and which plow? Please provide your logfile, so that I can see what's going on.

**Comment by xVirusXx** [comment]
Correct, and I am using the first John Deere Medium Tractor (7810).

No matter what I try it always attempts to do a full single motion turn.

**Comment by jason0611** [comment]
Ok. The function "Two step turn" is for turning the plow behind the tractor. It can be turned full, or halfway at the beginning of the turning maneuver and halfway at the end of the turning maneuver. It's not for the turning maneuver itself.
For turning, Headland Management calls the corresponding VCA function and this function only make full turns.

**Comment by xVirusXx** [comment]
Oh gotcha. I took that to mean make a two point turn. Thanks!!
