### ISSUE TITLE
Changing a keybind stops headland management

### ISSUE THREAD

**Issue by cwhandersen** [jason0611/FS22_HeadlandManagement#79]
Whenever I change a keybinding In FS22, Headland Management stops working.
I stops me from changing mode, and I can't access the Menu either.
The solution is to change any keybinding again. So change a keybinding twice.
This was also a problem in the FS19 version of Headland Management.

I've also recently experienced a similar bug in FS22 on a dedicated server with the new addition of being able to turn of Headland Management. 
The bug here is where i can't turn on Headland Management if the other player in the game has turned there's on.
The solution is for us both to remove any keybind - save - add the keybind again - save again.
But this problem only occurs when the save game is completely new.

**Comment by jason0611** [comment]
Have you tried to leave and re-enter the vehicle? Sometimes the game doesn't recognise changed keybindings correctly. 
If this doesn't help, please provide your Logfile do that I can look into it and eventually try to find a way to reproduce it.

**Comment by cwhandersen** [comment]
I've only now had the change to check if it works to exit the vehicle. And it does. So thank you for the help. And thank you for making an amazing mod.

**Comment by jason0611** [comment]
Thank you for your feedback. I'm glad, that it works and that I don't have to worry about an unknown bug. :-)
