### ISSUE TITLE
Funktioniert nicht mehr seit Update von Giants

### ISSUE THREAD

**Issue by Gandalf-55** [jason0611/FS22_HeadlandManagement#80]
Seit dem letzten Update von Giants funktioniert der Vorgewende-Manager nicht mehr.
Man kann ihn im Store kaufen, der Betrag wird auch abgebucht, jedoch bleibt der Kauf nicht gespeichert und man kann den Manager auch nicht einschalten/aktivieren.
Oder mache ich evt einen Bedienfehler?

Bitte um Rückinfo

Danke

**Comment by jason0611** [comment]
Seit Patch 1.4 funktioniert, wie bei vielen anderen Skript-Mods, die Registrierung im Fahrzeug nicht mehr. Dadurch ist das Skript mit Version 1.4 nicht funktionsfähig.
Giants hat kurzfristig einen Hotfix (Version 1.4.1) angekündigt, der den Fehler beheben soll, bis dahin warte ich ab.

**Comment by Gandalf-55** [comment]
Alles klar, dann weiß ich Bescheid.
Vielen Dank für die schnelle Antwort.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>
________________________________
