### ISSUE TITLE
LUA error with patch 1.4.1

### ISSUE THREAD

**Issue by mrPassion78** [jason0611/FS22_HeadlandManagement#82]
nearly all the script mods have the same LUA error with the patch..
would it be possible to update this awesome mod to?
here is the lua error from the log:

2022-04-23 10:45   Load mod: FS22_HeadlandManagement
2022-04-23 10:45   Error: Invalid customEnvironment given for SpecializationManager.addSpecialization. Should be a string or nil.
2022-04-23 10:45 LUA call stack:
  dataS/scripts/mods.lua (396) : printCallstack
  =C:/Users/pasca/Documents/My Games/FarmingSimulator2022/mods/GAMEPLAY FS22/FS22_HeadlandManagement/headlandManagementRegister.lua (9) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (347) : source
  dataS/scripts/mods.lua (839) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (836) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1152) : update
2022-04-23 10:45   Error: Too many arguments for SpecializationManager.addSpecialization. (Arguments should be: name, className, filename, customEnvironment)
2022-04-23 10:45 LUA call stack:
  dataS/scripts/mods.lua (401) : printCallstack
  =C:/Users/pasca/Documents/My Games/FarmingSimulator2022/mods/GAMEPLAY FS22/FS22_HeadlandManagement/headlandManagementRegister.lua (9) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (347) : source
  dataS/scripts/mods.lua (839) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (836) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1152) : update

**Comment by jason0611** [comment]
The dev version here is already fixed and will go to the ModHub as soon as possible.
