### ISSUE TITLE
Plow rotation

### ISSUE THREAD

**Issue by Kynuska** [jason0611/FS22_HeadlandManagement#86]
Hi. I noticed that the plow rotates and raises at the same time. I'm not a farmer, but first I would raise the plow to the upper position and then turn it.
I look forward to more opinions.
Kynuska.

**Comment by jason0611** [comment]
That's right, but for the game it's that only an optical issue.
I've to find out, if there is another animation-time-value to read out and wait for that period. If there is none, I have no chance to delimit the raise time from the turn time for all possible plow-variations and then it would not be possible to realize it. I will find see, what will be possible.

**Comment by jason0611** [comment]
I've already implemented a wait function between lifting and turning which depends on the per-vehicle defined duration of the lift animation. Maybe some plows return a time of '0', all other plows should turn _after_ raising.

**Comment by SAM24986** [comment]
Moin Moin,
ich würde das gerne nochmals ansprechen, das sieht in der Tat etwas "unschön" aus. Ich benutze für die Spurführung EV. Wenn ich z.B. 18m Vorgewende einstelle so beginnt dann die Wendefunktion von EV. Vllt gibt es die Möglichkeit die eingestellten Vorgewende-Werte von EV zu nutzen. Auch das Wiedereinsetzen des Pfluges ist nicht so schön da das Schwenken des Pfluges in die Endstellung im herabgelassenen Zustand vollzogen wird.
Bei den Fahrzeugen und Geräten handelt es sich um einen JD R350 und einem Kverneland ECO, beides aus dem Basisspiel.

Ansonsten tolle Arbeit, vielen Dank dafür.
