### ISSUE TITLE
Feature request: Kompatibilität mit Traubenvollernter

### ISSUE THREAD

**Issue by Ace-1986** [jason0611/FS22_HeadlandManagement#92]
Kann man es eventuell für Traubenvollernter konfigurierbar machen? Würde gerne auch im Vollernter per Knopfdruck das GPS pausieren und den Tempomat wechseln wollen. Danke

**Comment by jason0611** [comment]
Das ist kein Problem. Derzeit ist die momentan aktuelle Version im ModHub-Test und daher ändere ich gerade nichts  am Skript. Wenn der Test abgeschlossen ist, werde ich Trauben- und Olivenernter hinzufügen.
