### ISSUE TITLE
Bei FM-Modding Fahrzeuegn nicht anwählbar.

### ISSUE THREAD

**Issue by AK-Baldow** [jason0611/FS22_HeadlandManagement#98]
Hi, 
benutze deine Mod seit anfang an.
Spiele gerade auf der Mountenhill V5 von FM-Modding. Diese hat eigene Fahrzeuge. Leider schreibt sich dein Mod nicht in diese hinein.
Ob es bei anderen Karten mit eigenen Fahrzeugen ist weiß ich nicht.
Dann benutze ich noch " https://forbidden-mods.de/filebase/file/36866-krone-bigm500/ " ist auch von FM-Modding.
Da kann ich auch nicht auswählen ob eingebaut werden soll.

**Comment by jason0611** [comment]
Hi, 
Danke für das Feedback. Bitte teste mal die beigefügte Version, ob es jetzt in den besagten Fahrzeugen konfigurierbar ist und funktioniert.
[FS22_HeadlandManagement.zip](https://github.com/jason0611/FS22_HeadlandManagement/files/9946515/FS22_HeadlandManagement.zip)

**Comment by AK-Baldow** [comment]
Hi,
danke für den schnellen (extrem schnellen) Fix.
Mod läßt sich jetzt in allen fahrzeugen installieren.

Danke schön

**Comment by jason0611** [comment]
Perfekt, dann mache ich hier mal zu. :-)
