### ISSUE TITLE
Plow rotation #86

### ISSUE THREAD

**Issue by SAM24986** [jason0611/FS22_HeadlandManagement#99]
Moin Moin,
ich würde das gerne nochmals ansprechen, das sieht in der Tat etwas "unschön" aus. Ich benutze für die Spurführung EV. Wenn ich z.B. 18m Vorgewende einstelle so beginnt dann die Wendefunktion von EV. Vllt gibt es die Möglichkeit die eingestellten Vorgewende-Werte von EV zu nutzen. Auch das Wiedereinsetzen des Pfluges ist nicht so schön da das Schwenken des Pfluges in die Endstellung im herabgelassenen Zustand vollzogen wird.
Bei den Fahrzeugen und Geräten handelt es sich um einen JD R350 und einem Kverneland ECO, beides aus dem Basisspiel.

Ansonsten tolle Arbeit, vielen Dank dafür.

_Originally posted by @SAM24986 in https://github.com/jason0611/FS22_HeadlandManagement/issues/86#issuecomment-1317734644_

**Comment by jason0611** [comment]
Moin,
Danke für das Feedback. Das Timing mit Pflügen werde ich mir nochmal anschauen, ich habe den Eindruck, dass die Zeitwerte, die von den Pflügen für die Animation geliefert werden, nicht immer stimmen.
Für die Vorgewende-Erkennung über EV musst Du in EV einstellen, dass entweder der Tempomat reduziert wird, oder die automatische Wende von EV durchgeführt werden soll, dann übergibt Headland Management die Erkennung des Vorgewendes ganz an EV. Das wird durch ein "EV" im Symbol neben dem Tacho angezeigt.
Viele Grüße,
Martin

**Comment by jason0611** [comment]
Ich habe gerade nochmal tiefer in das Skript hineingesehen und dabei einen Fehler entdeckt, der dafür sorgte, dass eine schon lange eingebaute Wartezeit nicht berücksichtigt wurde. :-) 
Wenn die 14 Tage ModHub-Sperrfrist vorbei sind, werde ich ein Update einreichen, dass diesen Fehler wieder behebt.

**Comment by SAM24986** [comment]
Moin Martin,
ich habe die Lua mal so kopiert und neu eingefügt, so wie es jetzt ist sieht das schon richtig gut aus. Durch die neue Version bekommt aber EV Spurführung alle paar Meter einen Korrekturbefehl für die Lenkung, sodass die Fahrt mit dem Schlepper sehr unruhig und zappelig wird. Magst Du vlt nochmal schauen ob da noch irgendwas im argen ist?

Gruß
Sönke

**Comment by jason0611** [comment]
Moin Sönke,
hast Du die Lua aus dem Master-Branch kopiert, oder eventuell aus dem (experimentellen) Contour-Guidance-Branch?
Die Timing-Anpassungen haben keinerlei Einfluss auf die Spurführung, im CG-Branch habe ich jedoch in der Tat eine Spurführung verbaut, die bisher noch keine Rücksicht auf GPS-/EV- oder ähnliche Mods nimmt.
[FS22_HeadlandManagement.zip](https://github.com/jason0611/FS22_HeadlandManagement/files/10035809/FS22_HeadlandManagement.zip)
Versuche es mal mit der beigefügten Version. Wichtig: Es ist eine Entwickler-Version, die u.a. deutlich mehr Log-Einträge produziert.
Viele Grüße,
Martin

**Comment by SAM24986** [comment]
Hey Martin, um ehrlich zu sein weiß ich das gar nicht so genau. Das würde aber das zucken der Maschine und den unaufhörlichen Drang zur Spurführung (trotz abgeschaltetem EV/GPS) erklären 😁😁
Ich werde Deine Version im Link heute Abend dann testen.
Vielen Dank
Hab nen schönen Tag
Gruß Sönke

**Comment by SAM24986** [comment]
Moin Martin,
so ist's besser, der Pflug macht was er soll. Das einzige was mich jetzt noch ein bisschen stört ist, das HM den Pflug sofort absenkt wenn EV die richtige Spur erkannt hat. Oft ist dass dann innerhalb des eingestellten Vorgewendes und meistens wenn man rückwärts dreht. Aber ansonsten läuft es jetzt Tadellos.

Vielen Dank
Gruß Sönke

**Comment by Blackjack155** [comment]
the reversible plow still does not work
when will this be fixed after such a long time?

**Comment by jason0611** [comment]
Viel mehr kann hier nicht mehr optimiert werden. Generell ist der automatische Feldmodus auch weniger für den Pflug gedacht.

Soweit ich weiß, wird beim Pflügen das Vorgewende zum Schluss gemacht, dadurch macht eine "unsaubere" Kante im Endeffekt nichts aus.

**Comment by SAM24986** [comment]
Doch, dass funktioniert eigentlich recht gut. Ich hab das mit diesem Pflug jetzt ein paar mal gemacht, ich habe bei EV das Vorgewende auf 8 -9 Meter vor Feldrand eingestellt und die automatische Wende aktiviert. Im HM dann Tempomat-Geschwindigkeit auf 9 km/h eingestellt und aktiviert. Wichtig den Pflug sofort drehen, bei der Drehung in 2 Schritten lässt EV 2 Bahnen aus, weiß der Geier warum. Vllt hab ich auch nur etwas übersehen.
Den Pflug absenken und dem Tempomat einschalten, so wendet HM zusammen mit EV recht sauber am Ende und lässt auch keine großen Keile stehen.

Als Verbesserung würde ich es aber durchaus begrüßen wenn der Schlepper nach der Wende, bei erreichen des eingestellten Vorgewendes, solange stehen bleibt bis der Pflug wieder in Position ist und dann erst wieder losfährt. Das ist besonders für die größeren, aufgesattelten Pflüge schöner , da diese immer etwas brauchen bis sie wieder Endposition haben.
Nur mal so als Anregung.
Gruß
Sönke
